import { parseFacts, topicLevels, type LevelDef } from './bank';

const FAMILY = parseFacts([
  'Who is your father?|Tatay|Nanay|Lola|Ate|👨',
  'Who is your mother?|Nanay|Tatay|Lolo|Kuya|👩',
  'Who is your grandmother?|Lola|Lolo|Tita|Ate|👵',
  'Who is your grandfather?|Lolo|Lola|Tito|Kuya|👴',
  'Your older sister is…|Ate|Kuya|Tita|Lola|👧',
  'Your older brother is…|Kuya|Ate|Tito|Lolo|👦',
  'Your mother’s sister is your…|Tita|Ate|Lola|Nanay|👩',
  'Your father’s brother is your…|Tito|Kuya|Lolo|Tatay|👨',
  'A father, mother and children make a…|family|school|market|team|👨‍👩‍👧‍👦',
  'A family lives together in a…|home|bus|store|river|🏠',
  'Who takes care of the baby?|the family|the moon|the rocks|the wind|👶',
  'Which one is a family rule?|Say “po” and “opo”|Shout at elders|Break toys|Hide food|🙏',
  'We show respect to elders by saying…|po and opo|go away|give me|no way|🙏',
  'Mano po is a way to…|greet elders with respect|play a game|buy rice|sing|🤲',
  'Who helps cook meals at home?|everyone can help|nobody|only the cat|only the baby|🍳',
  'When we eat together as a family, we…|share and say thank you|shout|run away|fight|🍽️',
  'Which is a way to help at home?|set the table|make a mess|break things|hide the broom|🍽️',
  'A family that is big has…|many members|no members|only toys|only pets|👪',
  'Your parents’ parents are your…|grandparents|cousins|friends|neighbors|👵👴',
  'Your uncle’s child is your…|cousin|brother|teacher|grandma|🧒',
  'A baby brother or sister is…|a new family member|a toy|a pet|a stranger|👶',
  'Your family loves and…|cares for you|scolds only|forgets you|ignores you|❤️',
  'We celebrate family time at a…|birthday party|storm|traffic jam|test|🎂',
  'Who is in your family?|the people who care for you|only the pets|only the toys|only the neighbors|👨‍👩‍👧',
]);

const COMMUNITY = parseFacts([
  'Where do children learn?|school|market|church|hospital|🏫',
  'Where do we buy fish and vegetables?|market|library|school|park|🛒',
  'Where do sick people go to get well?|hospital|school|bank|cinema|🏥',
  'Where do we borrow books?|library|bakery|hospital|farm|📚',
  'Where do people pray?|church or mosque|market|police station|bank|⛪',
  'Where do we play and have fun in the community?|park|hospital|bank|jail|🛝',
  'Where do we keep our money safe?|bank|park|bakery|zoo|🏦',
  'Where is the fire truck kept?|fire station|school|bakery|barber|🚒',
  'Where can we get help from police?|police station|bakery|zoo|school|🚓',
  'Where do we buy bread?|bakery|bank|library|clinic|🍞',
  'Where do we get checked by a doctor in the barangay?|health center|toy store|park|church|🏥',
  'A small neighborhood is called a…|barangay|island|planet|castle|🏘️',
  'The leader of a barangay is the…|Kapitan|President|Pope|King|🏛️',
  'The place where the barangay leaders work is the…|barangay hall|zoo|bank|bakery|🏛️',
  'People who live near you are your…|neighbors|enemies|teachers|dolls|🏘️',
  'A community has many…|places and people|only rocks|only trees|no one|🌆',
  'A road helps us…|go to places|plant rice|sleep|swim|🛣️',
  'A bridge helps us cross…|a river|the sky|a book|a wall|🌉',
  'Where do ships and boats dock?|port|bakery|park|school|⚓',
  'Where do planes land?|airport|market|school|church|✈️',
  'Where do buses wait for passengers?|terminal|library|farm|church|🚌',
  'Where do farmers grow crops?|farm|school|airport|bank|🚜',
  'Where do fishers catch fish?|sea or river|school|market|library|🎣',
  'A rural community is often near…|farms|tall skyscrapers|subways|airports only|🌾',
]);

const HELPERS = parseFacts([
  'Who teaches children at school?|teacher|farmer|baker|driver|👩‍🏫',
  'Who helps sick people?|doctor|baker|driver|farmer|👨‍⚕️',
  'Who keeps us safe from crime?|police officer|baker|singer|farmer|👮',
  'Who puts out fires?|firefighter|teacher|cook|painter|🧑‍🚒',
  'Who grows rice and vegetables?|farmer|doctor|pilot|singer|🧑‍🌾',
  'Who catches fish?|fisher|baker|teacher|nurse|🎣',
  'Who bakes bread?|baker|farmer|pilot|driver|🧑‍🍳',
  'Who drives the jeepney?|driver|nurse|baker|singer|🚌',
  'Who flies an airplane?|pilot|farmer|baker|teacher|🧑‍✈️',
  'Who cuts hair?|barber|doctor|teacher|farmer|💈',
  'Who fixes cars?|mechanic|baker|singer|painter|🔧',
  'Who delivers letters?|mail carrier|doctor|pilot|farmer|📮',
  'Who helps a doctor care for patients?|nurse|fisher|pilot|baker|👩‍⚕️',
  'Who builds houses?|carpenter|singer|pilot|baker|🔨',
  'Who collects the garbage?|garbage collector|singer|pilot|teacher|🗑️',
  'Who sells food at the market?|vendor|pilot|singer|driver|🛒',
  'Who cooks food at a restaurant?|cook|nurse|farmer|pilot|🍳',
  'Who helps keep the road safe for people crossing?|traffic enforcer|baker|nurse|singer|🚦',
  'Who takes care of teeth?|dentist|farmer|baker|pilot|🦷',
  'Who sews clothes?|tailor|baker|pilot|painter|🧵',
  'Who guards the school gate?|security guard|singer|baker|cook|💂',
  'Who works in a library?|librarian|pilot|baker|farmer|📚',
  'Who protects our country as a soldier?|soldier|baker|farmer|singer|🎖️',
  'We should say ___ to community helpers.|thank you|go away|nothing|too bad|🙏',
]);

const NEEDS = parseFacts([
  'Which one is a need?|food|a new toy|a game|candy|🍚',
  'Which one is a need?|water|a robot toy|a video game|a balloon|💧',
  'Which one is a need?|shelter|a bike|a doll|sweets|🏠',
  'Which one is a need?|clothes|a toy car|ice cream|a kite|👕',
  'Which one is a want?|a toy|rice|water|a house|🧸',
  'Which one is a want?|candy|rice|water|medicine|🍬',
  'Which one is a want?|a video game|a bed|clothes|water|🎮',
  'We need food to…|live and grow|play only|make noise|fly|🍽️',
  'We need a house to stay…|safe and dry|loud|hungry|angry|🏠',
  'We need clothes to…|protect our body|hide toys|play music|run fast|👕',
  'We need medicine when we are…|sick|happy|sleepy|rich|💊',
  'We need school to…|learn|sleep|shop|race|🎒',
  'Which is more important: food or a new toy?|food|a new toy|they are the same|neither|🍚',
  'Wants are things we…|would like to have|must have to live|cannot see|never use|🎁',
  'Needs are things we…|must have to live|do not use|never want|can live without|🍚',
  'When we cannot buy a want, we can…|wait or save|cry and shout|steal|break things|🪙',
  'Saving money in a piggy bank helps us buy…|something later|nothing|only candy|only clothes|🐷',
  'To buy things, we use…|money|leaves|sand|stones|💰',
  'Philippine money is called…|peso|dollar|yen|euro|₱',
  'Who works to earn money for the family?|parents|toys|clouds|rocks|👨‍👩‍👧',
  'Sharing with others who have less is…|kind|silly|bad|scary|🤝',
  'Which one is a good use of money?|buying food|wasting it|throwing it|losing it|🛒',
  'A shirt is for…|wearing|eating|drinking|cooking|👕',
  'A bed is for…|sleeping|eating|swimming|cooking|🛏️',
]);

const SYMBOLS = parseFacts([
  'What is the national flower of the Philippines?|sampaguita|rose|tulip|sunflower|🌼',
  'What is the national tree?|narra|mango|pine|acacia|🌳',
  'What is the national fruit?|mango|apple|grape|pear|🥭',
  'What is the national animal?|carabao|lion|tiger|horse|🐃',
  'What is the national bird?|Philippine eagle|crow|hen|duck|🦅',
  'The Philippine flag has these colors: white, blue, red and…|yellow|green|pink|black|🇵🇭',
  'How many stars are on the Philippine flag?|three|one|five|eight|⭐',
  'The sun on the flag has how many rays?|eight|three|five|ten|☀️',
  'The top color of the Philippine flag is…|blue|red|green|white|🇵🇭',
  'The bottom color of the Philippine flag is…|red|blue|green|black|🇵🇭',
  'The national anthem is called…|Lupang Hinirang|Happy Birthday|Jingle Bells|Bahay Kubo|🎶',
  'The national hero is…|Jose Rizal|Bonifacio|Mabini|Luna|🦸',
  'The capital city of the Philippines is…|Manila|Cebu|Davao|Baguio|🏙️',
  'Our national language is…|Filipino|English only|Spanish|Japanese|🗣️',
  'The money in the Philippines is the…|peso|dollar|yen|pound|₱',
  'What is the national house?|bahay kubo|igloo|castle|tent|🛖',
  'What is the national dance?|tinikling|ballet|waltz|hip hop|💃',
  'What is the national sport?|arnis|soccer|golf|tennis|🥋',
  'We stand straight when we sing the…|national anthem|a lullaby|a jingle|a game song|🎵',
  'The Philippines is a…|country|planet|city|school|🇵🇭',
  'People of the Philippines are called…|Filipinos|Japanese|Americans|Chinese|🇵🇭',
  'The flag of the Philippines should be treated with…|respect|silliness|neglect|dirt|🇵🇭',
  'The Philippines has how many main island groups?|three|one|two|ten|🏝️',
  'What is the national leaf?|anahaw|banana leaf|oak leaf|fern|🍃',
]);

const MAPS = parseFacts([
  'The Sun rises in the…|east|west|north|south|🌅',
  'The Sun sets in the…|west|east|north|south|🌇',
  'The four main directions are north, south, east and…|west|up|down|left|🧭',
  'A map shows us where…|places are|food is cooked|toys grow|clouds sleep|🗺️',
  'A compass shows us…|directions|time|weather|money|🧭',
  'Which is the opposite of north?|south|east|west|up|⬆️',
  'Which is the opposite of east?|west|north|south|down|➡️',
  'Which hand do you use to write if you are right-handed?|right|left|both|none|✍️',
  'Which side is this arrow pointing? →|right|left|up|down|➡️',
  'Which side is this arrow pointing? ←|left|right|up|down|⬅️',
  'A place that is close is…|near|far|lost|old|📍',
  'A place that is not close is…|far|near|beside|next to|📍',
  'On a map, a blue part usually shows…|water|forest|road|school|🗺️',
  'On a map, a green part usually shows…|land with plants|ocean|sky|fire|🗺️',
  'The Philippines is in the continent of…|Asia|Africa|Antarctica|Europe|🌏',
  'The Philippines is surrounded by…|water|desert|snow|mountains only|🌊',
  'The northern part of the Philippines is…|Luzon|Visayas|Mindanao|Cebu only|🏝️',
  'The southern big island is…|Mindanao|Luzon|Visayas|Boracay|🏝️',
  'The middle island group is the…|Visayas|Luzon|Mindanao|Palawan|🏝️',
  'The school is next to the park. “Next to” means…|beside|far from|inside|above|🏫',
  'The cat is under the table. “Under” means…|below|above|beside|inside|🐱',
  'The bird is above the tree. “Above” means…|higher|lower|beside|inside|🐦',
  'To find the way, we can use a…|map|spoon|pillow|cup|🗺️',
  'The North Pole is very…|cold|hot|sandy|jungle|🧊',
]);

const PLACES = parseFacts([
  'The Chocolate Hills are in…|Bohol|Manila|Davao|Baguio|⛰️',
  'Mayon Volcano is famous for its…|perfect cone shape|flat top|ocean|desert|🌋',
  'The Banaue Rice Terraces are in…|Ifugao|Cebu|Manila|Davao|🌾',
  'Taal Volcano is in…|Batangas|Bohol|Palawan|Davao|🌋',
  'The Underground River is in…|Palawan|Manila|Bohol|Cebu|🌊',
  'Boracay is famous for its white…|beach|snow|mountain|rock|🏝️',
  'Rizal Park is in…|Manila|Davao|Cebu|Baguio|🌳',
  'Intramuros is an old walled city in…|Manila|Cebu|Davao|Bohol|🏰',
  'The Tarsier is a tiny animal found in…|Bohol|Manila|Baguio|Ilocos|🐒',
  'Baguio is called the…|Summer Capital|Capital of Fish|City of Gold|Beach City|🌲',
  'Cebu is in the…|Visayas|Luzon|Mindanao|Palawan|🏝️',
  'Davao is in…|Mindanao|Luzon|Visayas|Palawan|🏝️',
  'Manila is in…|Luzon|Visayas|Mindanao|Cebu|🏙️',
  'The Philippine eagle is a very big…|bird|fish|dog|cat|🦅',
  'Which is the biggest island in the Philippines?|Luzon|Mindanao|Cebu|Bohol|🏝️',
  'Which is a famous beach?|Boracay|Mt. Mayon|Taal|Baguio|🏖️',
  'Which is a famous volcano?|Mayon|Boracay|Luneta|Intramuros|🌋',
  'The Whale shark can be seen in…|Donsol|Baguio|Manila|Tagaytay|🦈',
  'Vigan is known for its old…|Spanish-style houses|skyscrapers|igloos|rockets|🏘️',
  'Tagaytay is known for the view of…|Taal Volcano|the Great Wall|the Alps|the Nile|🌋',
  'Which island group is the farthest north?|Luzon|Mindanao|Visayas|Palawan|🧭',
  'Which place is cold and has many pine trees?|Baguio|Manila|Boracay|Davao|🌲',
  'Which one is a lake in the Philippines?|Lake Taal|Lake Michigan|Lake Victoria|Lake Louise|🏞️',
  'The Philippines has more than…|7,000 islands|10 islands|20 islands|50 islands|🏝️',
]);

const HEROES = parseFacts([
  'Who is the national hero of the Philippines?|Jose Rizal|Andres Bonifacio|Emilio Aguinaldo|Apolinario Mabini|🦸',
  'Jose Rizal wrote the book…|Noli Me Tangere|Harry Potter|Pinocchio|Alice|📖',
  'Independence Day in the Philippines is on…|June 12|January 1|December 25|May 1|🇵🇭',
  'Christmas Day is on…|December 25|June 12|May 1|November 1|🎄',
  'New Year’s Day is on…|January 1|June 12|August 21|December 30|🎆',
  'Labor Day is on…|May 1|June 12|January 1|December 25|👷',
  'All Saints’ Day is on…|November 1|June 12|July 4|May 1|🕯️',
  'Rizal Day is on…|December 30|June 12|January 1|May 1|🦸',
  'Who is called the “Father of the Katipunan”?|Andres Bonifacio|Jose Rizal|Aguinaldo|Mabini|🦸',
  'Who was the first President of the Philippines?|Emilio Aguinaldo|Jose Rizal|Manuel Quezon|Marcos|🇵🇭',
  'Heroes fought for our…|freedom|candy|toys|games|🕊️',
  'We remember heroes by being…|kind and brave|rude|lazy|mean|🌟',
  'Jose Rizal was a…|doctor and writer|singer|pilot|baker|🩺',
  'A national holiday is a day…|when many people rest and remember|that never comes|with no sun|for homework only|📅',
  'On Independence Day, we hang the…|flag|socks|plates|toys|🇵🇭',
  'Who was the chief of Mactan who won the famous battle?|Lapu-Lapu|Rizal|Bonifacio|Luna|🦸',
  'Lapu-Lapu was a chief of…|Mactan|Manila|Davao|Baguio|🏝️',
  'Gabriela Silang was a brave…|woman hero|baker|singer|pilot|🦸‍♀️',
  'A hero is someone who…|helps and is brave|breaks rules|lies|scares others|🦸',
  'We can be small heroes by…|helping others|being mean|fighting|hiding|🤝',
  'A museum keeps…|old and important things|fresh fish|toys for sale|only food|🏛️',
  'Bonifacio Day is on…|November 30|June 12|January 1|May 1|📅',
  'On what day do we celebrate Philippine Independence?|June 12|January 1|May 1|December 25|🇵🇭',
  'The Philippines was freed after many…|years of brave people’s struggle|games|parties|naps|🕊️',
]);

const CULTURE = parseFacts([
  'Which food is a Filipino dish?|adobo|sushi|pizza|tacos|🍲',
  'Which food is a sour Filipino soup?|sinigang|ramen|pasta|burger|🍲',
  'Which Filipino dessert is made with shaved ice?|halo-halo|ice cream cake|pudding|crepe|🍧',
  'The barong tagalog is worn by…|men|only babies|only dogs|nobody|👔',
  'The baro’t saya is worn by…|women|only men|only dogs|nobody|👗',
  'A traditional dance with bamboo poles is…|tinikling|ballet|salsa|tango|💃',
  'Patintero is a…|street game|food|dance|song|🏃',
  'Luksong tinik is a game where we…|jump over|swim|read|eat|🦘',
  'Piko is also called…|hopscotch|tag|chess|marbles|🦶',
  'The Sinulog festival is in…|Cebu|Baguio|Manila|Davao|🎉',
  'The Ati-Atihan festival is in…|Aklan|Cebu|Davao|Manila|🎉',
  'The Panagbenga festival is a festival of…|flowers|fish|kites|candies|🌸',
  'The Pahiyas festival uses colorful…|rice decorations|balloons only|kites only|robots|🌾',
  'Bahay kubo is a house made of…|bamboo and nipa|ice|metal only|plastic|🛖',
  'A Filipino greeting to elders is…|mano po|go away|hey you|nothing|🤲',
  'Misa de Gallo is a…|Christmas dawn mass|beach game|school test|soup|⛪',
  'A parol is a Christmas…|lantern|hat|ball|drum|🌟',
  'The Filipino word for “thank you” is…|salamat|hello|opo|paalam|🙏',
  'The Filipino word for “goodbye” is…|paalam|salamat|kumusta|opo|👋',
  'The Filipino word for “hello, how are you?” is…|kumusta|paalam|salamat|sige|👋',
  'The Filipino word for “yes” (with respect) is…|opo|hindi|sige|ayaw|🙏',
  'Which one is a Filipino folk song?|Bahay Kubo|Jingle Bells|Frère Jacques|Twinkle|🎶',
  'Rice is eaten with most…|Filipino meals|toys|games|clothes|🍚',
  'Many Filipinos are known to be…|hospitable and kind|rude|lazy|scary|😊',
]);

const RULES = parseFacts([
  'A red traffic light means…|stop|go|dance|jump|🔴',
  'A green traffic light means…|go|stop|sleep|wait forever|🟢',
  'A yellow traffic light means…|get ready|jump|sing|swim|🟡',
  'We cross the street at the…|pedestrian lane|middle of the road|bus|roof|🚸',
  'Before crossing the street, we should…|look left and right|close our eyes|run|play|👀',
  'In class, when we want to speak, we…|raise our hand|shout|throw a pencil|run|✋',
  'In the library, we should be…|quiet|loud|running|dancing|🤫',
  'We throw trash in the…|bin|river|street|school yard|🗑️',
  'At home, a good rule is to…|clean up our toys|break things|hide dishes|never listen|🧸',
  'Rules help keep us…|safe|angry|sad|lost|🛑',
  'When we line up, we…|wait for our turn|push|shout|run|🧍',
  'A good citizen is…|kind and helpful|rude|lazy|selfish|🌟',
  'A good citizen follows…|rules|nothing|only snacks|only toys|📜',
  'We should respect the…|flag|nothing|only toys|only candy|🇵🇭',
  'In a car, we wear a…|seat belt|hat|swim ring|backpack|🚗',
  'On a motorcycle, we should wear a…|helmet|crown|scarf|hat|🏍️',
  'When there is a fire, we should…|call for help and leave|hide under the bed|play|sleep|🔥',
  'During an earthquake, we should…|duck, cover and hold|run into a tree|swim|climb a roof|🌋',
  'During a fire drill, we…|follow the teacher calmly|run wildly|hide|shout|🧯',
  'If we are lost, we should ask a…|police officer|stranger with candy|dog|cat|👮',
  'We save water by…|turning off the tap|leaving it on|playing in it|never washing|🚰',
  'Keeping our community clean is the job of…|everyone|only the cat|only the moon|no one|🧹',
  'Voting is how grown-up citizens…|choose leaders|buy candy|sleep|sing|🗳️',
  'We obey our parents and…|teachers|nobody|pets only|toys|👩‍🏫',
]);

export function apLevels(): LevelDef[] {
  const sub = 'ap' as const;
  return [
    ...topicLevels({ subject: sub, topicNo: 1, topic: 'My family', emoji: '👨‍👩‍👧', blurb: 'Family members and how we show respect.', facts: FAMILY }),
    ...topicLevels({ subject: sub, topicNo: 2, topic: 'My community', emoji: '🏘️', blurb: 'Places in our barangay.', facts: COMMUNITY }),
    ...topicLevels({ subject: sub, topicNo: 3, topic: 'Community helpers', emoji: '👮', blurb: 'Who helps us every day?', facts: HELPERS }),
    ...topicLevels({ subject: sub, topicNo: 4, topic: 'Needs and wants', emoji: '🛒', blurb: 'What we need and what we want.', facts: NEEDS }),
    ...topicLevels({ subject: sub, topicNo: 5, topic: 'Philippine symbols', emoji: '🇵🇭', blurb: 'Our flag and national symbols.', facts: SYMBOLS }),
    ...topicLevels({ subject: sub, topicNo: 6, topic: 'Maps and directions', emoji: '🧭', blurb: 'North, south, east, west and near and far.', facts: MAPS }),
    ...topicLevels({ subject: sub, topicNo: 7, topic: 'Places in the Philippines', emoji: '🏝️', blurb: 'Famous places across the islands.', facts: PLACES }),
    ...topicLevels({ subject: sub, topicNo: 8, topic: 'Heroes and holidays', emoji: '🦸', blurb: 'Filipino heroes and special days.', facts: HEROES }),
    ...topicLevels({ subject: sub, topicNo: 9, topic: 'Filipino culture', emoji: '🎉', blurb: 'Food, games, festivals and words.', facts: CULTURE }),
    ...topicLevels({ subject: sub, topicNo: 10, topic: 'Rules and safety', emoji: '🚦', blurb: 'Good citizens follow rules.', facts: RULES }),
  ];
}
