import { parseFacts, topicLevels, type LevelDef } from './bank';

const MANNERS = parseFacts([
  'Someone gives you a gift. You say…|Thank you|Go away|Nothing|Give me more|🎁',
  'You bump into a friend by accident. You say…|Sorry|Move|Nothing|Too bad|😅',
  'You want a toy from a friend. You say…|May I have it, please?|Give it!|It is mine!|Nothing|🧸',
  'You walk past people who are talking. You say…|Excuse me|Move it|Nothing|Hey!|🚶',
  'In the morning, you greet your teacher with…|Good morning|Go away|Nothing|Give me|🌅',
  'When you meet a friend, you say…|Hello|Go away|Nothing|Shh|👋',
  'You leave your friend’s house. You say…|Goodbye|Nothing|Go away|I do not care|👋',
  'You want to speak in class. You first…|raise your hand|shout|run|hide|✋',
  'When someone is talking, we…|listen|shout over them|walk away|make noise|👂',
  'When we sneeze, we cover our…|nose and mouth|eyes|ears|feet|🤧',
  'At the table, we should…|chew with our mouth closed|talk with food in our mouth|throw food|run|🍽️',
  'When someone helps you, you say…|Thank you|Nothing|Too slow|Go away|🙏',
  'When you want to borrow something, you…|ask first|just take it|hide it|break it|✋',
  'When you make a mistake, you say…|I am sorry|It is not me|Go away|Nothing|😔',
  'When an elder comes in, you may…|stand and greet them|ignore them|hide|laugh|🙇',
  'We say “po” and “opo” to show…|respect|anger|fear|silliness|🙏',
  'When we line up, we…|wait for our turn|push in|run|shout|🧍',
  'Which one is a polite way to ask for water?|May I have some water, please?|Water now!|Give water!|Water!|💧',
  'Which one is polite?|Please sit here|Move!|Get away|Ugh|🪑',
  'When we answer a call, we say…|Hello, who is this?|Nothing|Go away|Hey you|📞',
  'In church or prayer, we should be…|quiet and respectful|loud|running|playing|🙏',
  'When someone is sad, we…|speak kindly|laugh at them|ignore them|make fun|🫂',
  'When you borrow a book, you…|return it on time|keep it forever|tear it|hide it|📚',
  'When you finish eating, you may say…|Thank you for the food|Yuck|I hate it|Nothing|🍽️',
]);

const HONESTY = parseFacts([
  'You break a cup. You…|tell the truth|hide it|blame the cat|run away|🥛',
  'You find a wallet. You…|give it to a grown-up|keep the money|throw it|hide it|👛',
  'A friend’s pencil is on the floor. You…|return it|keep it|hide it|break it|✏️',
  'You get a wrong answer on a test. You…|learn from it|cheat next time|hide the paper|blame others|📝',
  'Telling the truth is…|good|bad|silly|scary|✅',
  'Telling a lie is…|not good|fun|brave|kind|❌',
  'When you do something wrong, you should…|say sorry and tell the truth|hide|lie|blame someone|🙏',
  'Your friend asks if you ate the cake. You did. You say…|Yes, I ate it|No, not me|The dog did|I do not know|🍰',
  'A cashier gives you too much change. You…|give it back|keep it|run away|say nothing|💰',
  'You promised to help. You…|keep your promise|forget it|run away|hide|🤞',
  'An honest child is…|trusted|alone|silly|angry|😇',
  'If a friend cheats, you should…|tell the teacher kindly|copy them|laugh|help them cheat|📝',
  'It is wrong to…|take things that are not yours|ask first|share|return a toy|🚫',
  'When you find something that is not yours, you…|ask who owns it|keep it|sell it|throw it|🔍',
  'Being honest means…|telling the truth|hiding things|running away|being loud|✅',
  'You lose your friend’s toy. You…|tell them and say sorry|hide it|blame them|ignore it|🧸',
  'You are asked who spilled the milk. It was you. You say…|It was me, I am sorry|It was the cat|Not me|I do not know|🥛',
  'Which one shows honesty?|returning lost money|copying homework|taking a toy|lying about a cake|💰',
  'You see someone cheat. It is good to…|tell a trusted adult|cheat too|laugh|ignore|🧑‍🏫',
  'Honest people say words that are…|true|funny|loud|secret|✅',
  'You cannot finish your homework. You tell the teacher…|the truth|a made-up story|nothing|a lie|📚',
  'You find a candy that is not yours. You…|do not eat it without asking|eat it|hide it|trade it|🍬',
  'Honesty helps us…|keep friends|lose friends|get lost|get angry|🤝',
]);

const KINDNESS = parseFacts([
  'A friend has no snack. You…|share yours|eat it all|hide yours|laugh|🍪',
  'A classmate falls down. You…|help them up|laugh|run away|ignore them|🤕',
  'An elderly person carries a heavy bag. You…|offer to help|ignore them|laugh|take it|🎒',
  'A new student has no friends. You…|invite them to play|ignore them|tease them|push them|🧒',
  'Sharing makes others feel…|happy|sad|angry|scared|😊',
  'Kind words make people feel…|good|bad|scared|angry|💬',
  'Which one is a kind word?|You can do it|You are bad|Go away|I hate you|💬',
  'Which is an unkind word?|You are dumb|Thank you|Please|Good job|😠',
  'When you see a lost kitten, you…|tell a grown-up|throw stones|ignore it|scare it|🐱',
  'A friend is sad. You can…|give them a hug|laugh|run away|shout|🤗',
  'You have two toys, a friend has none. You…|share one|keep both|hide them|break one|🧸',
  'Which is a way to be kind?|help clean the room|break the toy|hide the broom|make a mess|🧹',
  'When someone shares with you, you say…|Thank you|Nothing|More!|Boo|🙏',
  'When you are kind, you…|help others|hurt others|hide|shout|💛',
  'It is kind to…|say please and thank you|tease others|push|take toys|🙏',
  'Which action shows kindness to animals?|feeding a stray cat|throwing stones|scaring a dog|pulling a tail|🐶',
  'A classmate forgot a pencil. You…|lend yours|laugh|ignore|take theirs|✏️',
  'A friend wins a prize. You…|cheer for them|get jealous|ignore|tease|🏆',
  'Who can we be kind to?|everyone|only friends|only family|no one|🌈',
  'Giving to people in need is called…|charity|tricking|hiding|teasing|🎁',
  'When someone is hurt, we say…|Are you okay?|Ha ha|Not my problem|Go away|🤕',
  'A kind person is also…|gentle|cruel|rude|angry|🤲',
  'You help your little brother tie his shoes. That is…|helping|teasing|hiding|breaking|👟',
  'Being kind makes the world…|better|worse|darker|louder|🌍',
]);

const RESPECT = parseFacts([
  'We show respect to elders by saying…|po and opo|go away|give me|no|🙏',
  'When your teacher talks, you…|listen|shout|play|run|👂',
  'When your parents call you, you…|answer politely|ignore them|run|hide|🗣️',
  'We respect other people’s things by…|asking before using|taking without asking|breaking them|hiding them|🧸',
  'Which is a respectful greeting to a grandparent?|Mano po|Hey you|Go away|Nothing|🤲',
  'We respect the flag by…|standing straight|playing with it|dropping it|wiping with it|🇵🇭',
  'When you disagree, you…|speak politely|shout|hit|run away|🗣️',
  'You respect others when you…|listen to them|laugh at them|ignore them|push them|👂',
  'Who should we respect?|everyone|only friends|only teachers|no one|🌈',
  'It is rude to…|interrupt|wait for your turn|say please|say thank you|🚫',
  'Which one is respectful?|waiting for your turn|cutting in line|snatching toys|shouting|🧍',
  'We respect our school by…|keeping it clean|writing on walls|breaking chairs|littering|🏫',
  'When a classmate speaks, we…|let them finish|talk over them|leave|make noise|🧒',
  'Every person is…|special|a toy|a rock|unimportant|🌟',
  'We do not tease people because they look…|different|the same|nice|happy|🧑‍🤝‍🧑',
  'To respect people with disabilities, we…|treat them kindly|stare and laugh|ignore them|avoid them|♿',
  'We keep the church or place of prayer…|quiet and tidy|noisy|messy|muddy|⛪',
  'Parents should be treated with…|love and respect|anger|laughter|silence|👨‍👩‍👧',
  'Good listeners look at the…|speaker|ceiling|floor|toys|👀',
  'When you borrow something, you take care of it because it is…|someone else’s|yours|free|junk|🧸',
  'A respectful child says…|please and thank you|give me|no way|yuck|🙏',
  'Elders have lots of…|wisdom|candy|toys|noise|👵',
  'We respect different…|beliefs and cultures|only our own|nothing|none|🌏',
  'Respect starts when we treat others the way we want to be…|treated|ignored|teased|pushed|🤝',
]);

const RESPONSIBILITY = parseFacts([
  'After playing, you…|put your toys away|leave them|throw them|break them|🧸',
  'Which is a chore a child can do?|set the table|drive the car|cook with fire|fix a roof|🍽️',
  'Your homework is…|your responsibility|your friend’s job|a toy|a secret|📚',
  'When you finish eating, you…|put your plate in the sink|leave it on the floor|throw it|hide it|🍽️',
  'A responsible child…|does their job|forgets everything|hides|breaks rules|✅',
  'Taking care of a pet means…|feeding it every day|forgetting it|hitting it|losing it|🐕',
  'Your school bag is packed…|the night before|never|during class|in the morning rush|🎒',
  'Who makes sure your bed is neat?|you can help|nobody|the cat|the moon|🛏️',
  'Watering a plant is a…|good chore|bad habit|silly joke|danger|🪴',
  'You borrow a pencil. You…|return it|keep it|lose it|break it|✏️',
  'When you are given a task, you…|finish it|hide|run away|forget|✅',
  'Which is your job as a student?|study and listen|skip class|make noise|break things|📖',
  'Sweeping the floor helps…|keep the house clean|make a mess|scare the cat|nothing|🧹',
  'If you spill water, you…|wipe it up|run away|blame others|ignore it|🧽',
  'Brushing your teeth is a…|daily habit|weekly joke|toy|secret|🪥',
  'Responsible children come to school…|on time|late|never|asleep|🕗',
  'We take care of our books by…|keeping them clean|tearing the pages|drawing on them|losing them|📚',
  'When you finish a game, you…|put the pieces back|leave them everywhere|throw them|hide them|🎲',
  'Who helps keep your home clean?|everyone|only the cat|no one|only the baby|🏠',
  'If you promise to do something, you…|do it|forget it|hide|lie|🤞',
  'A responsible child takes care of their…|things|neighbors’ toys only|pets only|nothing|🧸',
  'Your uniform should be…|clean and ready|dirty|torn|lost|👕',
  'You can help take care of younger siblings by…|being gentle|being rough|ignoring them|shouting|👶',
  'When the bell rings, you…|go to your seat|run around|hide|shout|🔔',
]);

const SELF = parseFacts([
  'How many times should we brush our teeth a day?|two|none|ten|one every week|🪥',
  'We wash our hands before we…|eat|run|jump|sing|🧼',
  'We take a bath to stay…|clean|dirty|sleepy|hungry|🛁',
  'Which food is good for us?|vegetables|too much candy|soda|chips|🥦',
  'We sleep at night so we can…|rest and grow|play all night|shrink|float|😴',
  'Which one keeps our hair clean?|shampoo|mud|paint|dust|🧴',
  'We cut our nails to keep them…|clean and short|dirty|long|colorful|💅',
  'We should drink plenty of…|water|soda|paint|glue|💧',
  'When we cough, we cover our…|mouth|eyes|ears|toes|🤧',
  'It is healthy to play…|outside|only in the dark|only with food|never|⚽',
  'Our school uniform should be…|clean|dirty|torn|wet|👕',
  'We wear shoes to protect our…|feet|ears|nose|eyes|👟',
  'We eat fruits for…|vitamins|toys|shoes|noise|🍎',
  'We ask a grown-up when we feel…|sick|happy|sleepy only|silly|🤒',
  'Which one is a good habit?|washing hands|biting nails|skipping baths|picking your nose|🧼',
  'We should eat three…|meals a day|candies a day|toys a day|naps a day|🍽️',
  'A clean room helps us feel…|calm|messy|scared|angry|🧹',
  'We keep our things…|neat|messy|lost|broken|🧺',
  'Dirty hands can carry…|germs|toys|candy|stars|🦠',
  'To stay safe at home, we do not play with…|fire and sharp things|toys|books|pillows|🔥',
  'We do not talk to…|strangers who offer candy|our teachers|our parents|our friends|🍬',
  'If someone makes you feel unsafe, you tell a…|trusted adult|stranger|toy|pet|🧑‍🏫',
  'Standing straight is good for our…|back|ears|nose|hair|🧍',
  'We take care of our eyes by not looking at screens…|too long|only at night|ever|while sleeping|📺',
]);

const FEELINGS = parseFacts([
  'When you get a gift, you feel…|happy|sad|angry|scared|🎁',
  'When you lose a toy, you may feel…|sad|happy|sleepy|silly|😢',
  'When someone breaks your toy, you may feel…|angry|happy|sleepy|proud|😠',
  'When you hear a loud noise, you may feel…|scared|sleepy|proud|silly|😨',
  'When you win a game, you may feel…|proud|sad|angry|scared|🏆',
  'When you feel angry, a good thing to do is…|breathe slowly|hit someone|break things|shout|😤',
  'When you feel sad, you can…|talk to someone|hide forever|break things|hit|😢',
  'When you are scared, you can…|tell a grown-up|hide and say nothing|hit|run away alone|😨',
  'Feelings are…|okay to have|bad|silly|secret|💛',
  'When your friend is angry, you can…|listen|shout|hit|laugh|👂',
  'A deep breath helps us…|calm down|get angry|shout|jump|🌬️',
  'When you feel left out, you can…|ask to join|cry and hide|hit|shout|🧒',
  'When you are excited, you may feel…|happy and bouncy|sleepy|bored|sick|🤩',
  'When you are tired, you need…|rest|candy|noise|games|😴',
  'When you are lonely, you can…|find a friend or family|hide|shout|break things|🫂',
  'It is okay to feel…|many feelings|only happy|nothing|angry always|🌈',
  'When you feel jealous, you can…|be happy for your friend|take their toy|tease them|hide|💚',
  'When you feel nervous before a show, you can…|take a deep breath|run away|hide|cry only|🎭',
  'If you make a mistake, you can…|try again|give up|blame someone|hide|🔁',
  'When someone says sorry, you can…|forgive them|hit them|yell|ignore forever|🤝',
  'A feeling of being thankful is…|gratitude|anger|fear|sleepiness|🙏',
  'When you feel worried, you can…|talk to a grown-up|stay quiet forever|shout|hit|🗣️',
  'When your pet is lost, you feel…|worried|silly|sleepy|proud|🐶',
  'You can show happiness by…|smiling|crying only|hiding|shouting at people|😊',
]);

const FRIENDS = parseFacts([
  'A good friend…|shares and helps|teases you|takes your toys|ignores you|🤝',
  'When you play a game, you…|take turns|always go first|cheat|shout|🎲',
  'If your friend loses a game, you say…|Good try!|You are bad|Ha ha|Go away|👏',
  'When you work in a group, you…|share jobs|do nothing|boss everyone|hide|👥',
  'Teamwork means…|working together|working alone|fighting|hiding|👥',
  'When a friend is sad, you…|stay with them|laugh|leave|shout|🫂',
  'A friend asks to play. You…|let them join|say no meanly|run away|ignore|🧒',
  'Friends should not…|hit each other|help each other|share|listen|✋',
  'When friends argue, they can…|talk and say sorry|fight|never speak again|break things|🗣️',
  'It is good to make friends with…|many kinds of people|only people like you|nobody|only one|🌈',
  'When you want to join a game, you say…|May I play, please?|Move over!|Mine!|Nothing|🎮',
  'When it is your friend’s birthday, you can…|greet them happily|forget|tease|ignore|🎂',
  'In a team, everyone’s idea…|is important|does not matter|is silly|is wrong|💡',
  'A friend shares a secret. You…|keep it|tell everyone|laugh|post it|🤫',
  'When you win, you…|stay humble and kind|brag|laugh at the others|shout|🏆',
  'When your team loses, you…|try again|cry and quit|blame others|hit|🔁',
  'Good friends are…|honest|mean|rude|lazy|😇',
  'Which one is a good thing to say to a friend?|Thank you for helping|You are dumb|Go away|I hate you|💬',
  'A friend is lonely. You can…|invite them|ignore|laugh|run|🫂',
  'When your friend needs help, you…|help|ignore|laugh|hide|🙋',
  'To solve a problem with a friend, we can…|talk it out|hit|shout|ignore forever|🗣️',
  'In a team, we use…|kind words|mean words|silence|screams|💬',
  'A good teammate…|helps others|only helps themselves|gives up|cheats|👏',
  'Friends play fair and follow the…|rules|nothing|snacks|toys|📜',
]);

const NATURE = parseFacts([
  'We keep our school clean by…|throwing trash in the bin|throwing trash on the floor|writing on walls|breaking trees|🗑️',
  'We save water by…|turning off the tap|leaving it on|wasting it|playing with it|🚰',
  'We save energy by turning off the…|lights when not in use|fridge always|moon|sun|💡',
  'Plants need…|water and sunlight|candy|toys|noise|🌱',
  'Which one is good for the Earth?|planting trees|littering|burning plastic|wasting water|🌳',
  'We should not pick…|flowers in the park|up our toys|up trash|up our books|🌸',
  'Pets need…|food, water and love|only toys|only candy|nothing|🐶',
  'Animals should be treated…|kindly|roughly|meanly|loudly|🐶',
  'We can reuse a… bottle to hold flowers.|plastic|banana|cloud|leaf|🍼',
  'Recycling helps…|reduce trash|make more trash|make noise|waste water|♻️',
  'Which one is a good way to reduce trash?|bring a reusable bag|use a new plastic bag every time|burn trash|throw it in rivers|🛍️',
  'A river should be…|clean|full of trash|dirty|ignored|🏞️',
  'We should put a trash bin…|where everyone can use it|in a river|nowhere|in the sky|🗑️',
  'A forest is home to…|many animals and plants|only cars|only toys|only fish|🌲',
  'When you finish brushing, turn off the…|tap|moon|sun|TV|🚰',
  'We can use both sides of the…|paper|spoon|plate|shoe|📄',
  'It is wrong to…|cut trees without a reason|plant trees|water plants|feed pets|🪓',
  'A school garden teaches us to…|care for plants|break pots|waste water|hide|🌻',
  'When you see litter, you…|pick it up|kick it|ignore|scatter more|🗑️',
  'Which animal needs a gentle touch?|a puppy|a rock|a chair|a spoon|🐶',
  'Which is a good habit?|using less water|leaving water running|wasting food|littering|🚰',
  'We thank nature for giving us…|air, water and food|only toys|only candy|nothing|🌍',
  'A healthy Earth needs…|everybody’s care|nobody|only one person|only toys|🌍',
  'We should walk on…|the path in a garden|the flowers|the plants|the animals|🌼',
]);

const VALUES = parseFacts([
  'Saying “thank you” shows…|gratitude|anger|fear|silliness|🙏',
  'A brave child…|tries new things|hides always|gives up|screams|🦁',
  'If you fall while learning to ride a bike, you…|try again|quit forever|blame the bike|cry only|🚲',
  'Being patient means…|waiting calmly|rushing|shouting|quitting|⏳',
  'Perseverance means…|not giving up|quitting early|hiding|cheating|💪',
  'Forgiving means…|letting go of anger|holding anger forever|hitting back|hiding|🤝',
  'When someone says sorry, a good response is…|I forgive you|never|go away|ha ha|🤝',
  'Helping a classmate with a hard problem is…|kind|rude|silly|scary|🙋',
  'Saying a prayer is a way to show…|faith and thanks|anger|fear|play only|🙏',
  'Love for our country is called…|patriotism|jealousy|laziness|silliness|🇵🇭',
  'We love our country by…|being good citizens|littering|breaking rules|being rude|🇵🇭',
  'We thank our teachers by…|doing our best|ignoring them|being rude|talking back|👩‍🏫',
  'We thank our parents by…|obeying and helping|ignoring them|breaking things|shouting|👨‍👩‍👧',
  'Being generous means…|giving and sharing|keeping everything|hiding|taking|🎁',
  'Being humble means…|not bragging|showing off|shouting|teasing|🙂',
  'Being fair means…|treating everyone equally|choosing favorites|cheating|taking everything|⚖️',
  'Being cheerful means…|being happy and positive|being grumpy|hiding|crying always|😊',
  'Being gentle means…|being soft and kind|being rough|loud|rude|🕊️',
  'When something is hard, a good attitude is…|I will try|I give up|I cannot|It is not fair|💪',
  'When you do your best, you should feel…|proud|ashamed|angry|scared|🌟',
  'Which one is a good habit before eating?|saying thank you for the food|shouting|throwing food|refusing food|🍽️',
  'A hard worker…|keeps trying|gives up|hides|blames others|🛠️',
  'A kind word each day makes our home…|happy|noisy|messy|dark|🏠',
  'Being thankful for little things makes us…|happy|angry|worried|sleepy|🌈',
]);

export function espLevels(): LevelDef[] {
  const sub = 'esp' as const;
  return [
    ...topicLevels({ subject: sub, topicNo: 1, topic: 'Good manners', emoji: '🙏', blurb: 'Please, thank you and sorry.', facts: MANNERS }),
    ...topicLevels({ subject: sub, topicNo: 2, topic: 'Honesty', emoji: '✅', blurb: 'Telling the truth.', facts: HONESTY }),
    ...topicLevels({ subject: sub, topicNo: 3, topic: 'Kindness and sharing', emoji: '💛', blurb: 'Be kind and share.', facts: KINDNESS }),
    ...topicLevels({ subject: sub, topicNo: 4, topic: 'Respect', emoji: '🤲', blurb: 'Respect for elders and others.', facts: RESPECT }),
    ...topicLevels({ subject: sub, topicNo: 5, topic: 'Responsibility', emoji: '🧹', blurb: 'Doing my jobs and chores.', facts: RESPONSIBILITY }),
    ...topicLevels({ subject: sub, topicNo: 6, topic: 'Taking care of me', emoji: '🪥', blurb: 'Healthy and safe habits.', facts: SELF }),
    ...topicLevels({ subject: sub, topicNo: 7, topic: 'My feelings', emoji: '😊', blurb: 'Happy, sad, angry and calm.', facts: FEELINGS }),
    ...topicLevels({ subject: sub, topicNo: 8, topic: 'Friends and teamwork', emoji: '🤝', blurb: 'Playing and working together.', facts: FRIENDS }),
    ...topicLevels({ subject: sub, topicNo: 9, topic: 'Caring for nature', emoji: '🌍', blurb: 'Helping the Earth and animals.', facts: NATURE }),
    ...topicLevels({ subject: sub, topicNo: 10, topic: 'Good values', emoji: '🌟', blurb: 'Gratitude, courage and patience.', facts: VALUES }),
  ];
}
