import { parseFacts, topicLevels, type LevelDef } from './bank';

const ANIMALS = parseFacts([
  'Which animal gives us milk?|cow|cat|fish|bird|🐄',
  'Which animal says "meow"?|cat|dog|cow|duck|🐱',
  'Which animal has wings and can fly?|bird|fish|pig|dog|🐦',
  'Which animal lives in water?|fish|cat|goat|hen|🐟',
  'Which animal lays eggs?|hen|dog|cow|pig|🐔',
  'A baby dog is called a…|puppy|kitten|chick|calf|🐶',
  'A baby cat is called a…|kitten|puppy|chick|cub|🐱',
  'A baby hen is called a…|chick|puppy|kitten|calf|🐥',
  'Which animal has a long trunk?|elephant|lion|goat|duck|🐘',
  'Which animal has a very long neck?|giraffe|pig|cat|rabbit|🦒',
  'Which animal hops and likes carrots?|rabbit|snake|fish|cow|🐰',
  'Which animal has stripes?|zebra|horse|dog|pig|🦓',
  'Which animal carries its house on its back?|snail|bird|bee|dog|🐌',
  'Which insect makes honey?|bee|ant|fly|worm|🐝',
  'Which animal has eight legs?|spider|ant|bird|cat|🕷️',
  'Which animal changes from a caterpillar?|butterfly|bee|bird|frog|🦋',
  'Which animal is the king of the jungle?|lion|rabbit|duck|fish|🦁',
  'The carabao is the national animal of the…|Philippines|moon|sea|sky|🐃',
  'Which animal can swim and quack?|duck|cat|goat|cow|🦆',
  'Which animal has fur?|dog|fish|bird|snake|🐕',
  'Which animal has scales?|fish|cat|dog|rabbit|🐠',
  'Which animal has feathers?|bird|cat|fish|pig|🪶',
  'Where does a fish live?|in water|in a tree|in a nest|in a cave|🌊',
  'Where does a bird build its nest?|in a tree|in water|under the sea|in the sand|🪺',
]);

const PLANTS = parseFacts([
  'Which part of a plant holds it in the soil?|roots|leaves|flower|fruit|🌱',
  'Which part of a plant makes food from sunlight?|leaves|roots|seed|soil|🍃',
  'Which part of a plant is tall and holds it up?|stem|root|petal|seed|🌿',
  'What does a seed grow into?|a plant|a rock|a shoe|a cloud|🌰',
  'What do plants need to grow?|water and sunlight|candy and toys|only dark|plastic|🌻',
  'Which part of a plant is often colorful and pretty?|flower|root|stem|soil|🌸',
  'A mango is a…|fruit|animal|rock|toy|🥭',
  'A carrot grows under the…|ground|sea|sky|roof|🥕',
  'Which is a vegetable?|carrot|apple|banana|mango|🥕',
  'Which is a fruit?|banana|carrot|cabbage|onion|🍌',
  'Which tree gives us coconuts?|coconut tree|apple tree|pine tree|rose bush|🥥',
  'A plant that grows very tall and has a trunk is a…|tree|grass|moss|seed|🌳',
  'Plants take in water through their…|roots|petals|fruits|seeds|💧',
  'Where do we plant seeds?|in soil|in a car|on a roof|in the air|🌱',
  'Which one is a flower?|rose|rock|chair|spoon|🌹',
  'What is the national flower of the Philippines?|sampaguita|rose|tulip|sunflower|🌼',
  'What is the national fruit of the Philippines?|mango|apple|grape|pear|🥭',
  'What do plants give us to breathe?|air to breathe|rocks|plastic|smoke|🌬️',
  'A plant that does NOT get water will…|dry up|grow fast|sing|fly|🥀',
  'Which part do we eat of a lettuce?|leaves|roots|petals|seeds|🥬',
  'Which part of a sunflower makes seeds we can eat?|flower|root|leaf|stem|🌻',
  'Which is bigger?|a tree|a seed|a leaf|a petal|🌳',
  'Rice grows in a…|field|desert|cave|igloo|🌾',
  'Corn is a…|plant|animal|rock|tool|🌽',
]);

const BODY = parseFacts([
  'We see with our…|eyes|ears|nose|hands|👀',
  'We hear with our…|ears|eyes|nose|feet|👂',
  'We smell with our…|nose|eyes|ears|hands|👃',
  'We taste with our…|tongue|nose|ears|feet|👅',
  'We touch with our…|skin|hair|ears|teeth|🖐️',
  'We walk with our…|legs|ears|eyes|hands|🦵',
  'We hold a pencil with our…|hand|foot|ear|nose|✏️',
  'We chew food with our…|teeth|hair|eyes|toes|🦷',
  'Which part pumps blood?|heart|hand|knee|ear|❤️',
  'Which part helps us think?|brain|nose|toe|elbow|🧠',
  'We breathe with our…|lungs|knees|ears|feet|🫁',
  'How many eyes do we have?|two|one|three|four|👀',
  'How many fingers are on one hand?|five|four|six|ten|🖐️',
  'How many toes do we have in all?|ten|five|eight|twenty|🦶',
  'Which part bends in the middle of your arm?|elbow|knee|neck|toe|💪',
  'Which part bends in the middle of your leg?|knee|elbow|wrist|ear|🦵',
  'Which sense do we use to listen to music?|hearing|smell|taste|sight|🎵',
  'Which sense do we use to look at a rainbow?|sight|hearing|smell|touch|🌈',
  'Which sense do we use to smell a flower?|smell|taste|hearing|sight|🌸',
  'Which sense tells us an ice cube is cold?|touch|sight|hearing|smell|🧊',
  'Our skin keeps our body…|safe|loud|square|dirty|🧍',
  'What helps us stand strong and straight?|bones|hair|nails|ears|🦴',
  'Which part moves our bones?|muscles|eyelashes|hair|teeth|💪',
  'We grow taller when we…|eat well and sleep|skip meals|never rest|stay up late|📏',
]);

const WEATHER = parseFacts([
  'When it is hot, the weather is…|sunny|snowy|icy|foggy|☀️',
  'Rain falls from the…|clouds|trees|ground|sea|🌧️',
  'What do we use when it rains?|umbrella|sunglasses|fan|kite|☂️',
  'What do we use when it is very sunny?|hat|boots|raincoat|scarf|🧢',
  'A strong wind with rain is a…|typhoon|rainbow|snowman|sunrise|🌀',
  'What do you see after rain and sun together?|rainbow|snow|storm|star|🌈',
  'Which weather makes kites fly?|windy|rainy|foggy|snowy|🪁',
  'Thunder is a…|loud sound|bright color|cold wind|sweet taste|⛈️',
  'Lightning is a…|flash of light|loud song|wet leaf|cold wind|⚡',
  'In the Philippines, the wet season is the…|rainy season|snow season|spring|autumn|🌧️',
  'In the Philippines, the dry season is…|hot and dry|snowy|full of leaves falling|freezing|🏜️',
  'What should we wear when it is cold?|a jacket|shorts|sandals|a swimsuit|🧥',
  'What should we wear when it is hot?|light clothes|a coat|boots|gloves|👕',
  'Clouds are made of tiny drops of…|water|sand|paper|milk|☁️',
  'Which is NOT weather?|a chair|rain|wind|sunshine|🪑',
  'A weather vane shows which way the… blows.|wind|sun|moon|rain|🧭',
  'When the sky is full of gray clouds, it may…|rain|snow in Manila|bloom|freeze|☁️',
  'It is safe to stay indoors during a…|storm|picnic|sunny day|rainbow|🏠',
  'We use a thermometer to measure…|how hot or cold|how loud|how tall|how heavy|🌡️',
  'A calm day has very little…|wind|sun|sky|air|🍃',
  'Puddles form after…|rain|sunshine|a rainbow|wind|💧',
  'The sun dries the wet clothes on a…|sunny day|rainy day|stormy night|foggy night|👕',
  'Which season is cool and breezy in the Philippines?|December to February|April to May|June only|none|🌬️',
  'When there is a typhoon, we should listen to…|grown-ups and the news|only the wind|nobody|the waves|📻',
]);

const SKY = parseFacts([
  'Which star gives us light and heat in the day?|the Sun|the Moon|a comet|a planet|☀️',
  'What shines in the night sky and changes shape?|the Moon|the Sun|a cloud|a bird|🌙',
  'We live on the planet…|Earth|Mars|Jupiter|Venus|🌍',
  'The Sun rises in the…|east|west|north|south|🌅',
  'The Sun sets in the…|west|east|north|south|🌇',
  'Day and night happen because the Earth…|spins|stops|melts|sleeps|🌍',
  'We see little twinkling lights in the sky at…|night|noon|breakfast|lunch|✨',
  'The Moon goes around the…|Earth|tree|house|river|🌙',
  'Which is the biggest planet?|Jupiter|Earth|Mars|Mercury|🪐',
  'Which planet is called the Red Planet?|Mars|Venus|Neptune|Saturn|🔴',
  'Which planet has beautiful rings?|Saturn|Mars|Earth|Mercury|🪐',
  'A group of stars that makes a picture is a…|constellation|cloud|puddle|garden|⭐',
  'Who has walked on the Moon?|astronauts|farmers|teachers|bakers|👩‍🚀',
  'What do astronauts ride into space?|a rocket|a bus|a boat|a bike|🚀',
  'What do we call a streak of light when a space rock burns?|shooting star|rainbow|lightning|fire|🌠',
  'The Sun is a…|star|planet|moon|cloud|⭐',
  'We should never look straight at the…|Sun|Moon|clouds|trees|🕶️',
  'The Moon looks bright because it reflects light from the…|Sun|Earth|stars|lamp|🌕',
  'Morning comes after…|night|noon|lunch|dinner|🌄',
  'It is darkest at…|night|noon|morning|lunch|🌃',
  'The shape of the Earth is like a…|ball|box|triangle|cube|🌍',
  'What can we use to see faraway stars better?|a telescope|a spoon|a pencil|a hat|🔭',
  'How many days are in one week?|seven|five|ten|twelve|📅',
  'The Moon is part of the…|sky|kitchen|ocean|garden|🌙',
]);

const MATERIALS = parseFacts([
  'Which one is hard?|a rock|a pillow|a sponge|cotton|🪨',
  'Which one is soft?|a pillow|a rock|a spoon|a brick|🛏️',
  'Which one floats on water?|a leaf|a stone|a coin|a key|🍃',
  'Which one sinks in water?|a stone|a leaf|a feather|a cork|🪨',
  'Glass is…|see-through|bouncy|a plant|alive|🥛',
  'Which one is rough?|sandpaper|silk|a mirror|water|🧱',
  'Which one is smooth?|a mirror|sandpaper|tree bark|a rock|🪞',
  'A spoon can be made of…|metal|water|air|cloud|🥄',
  'A chair can be made of…|wood|water|air|ice cream|🪑',
  'A bottle can be made of…|plastic|cloud|fire|wind|🍼',
  'Which material do we get from trees?|wood|metal|glass|rubber|🪵',
  'Which one bounces?|a rubber ball|a rock|a book|a spoon|⚽',
  'Which one can break easily?|a glass cup|a rubber ball|a wooden spoon|a pillow|🥛',
  'A raincoat keeps us…|dry|hungry|loud|sleepy|🧥',
  'Paper is made from…|trees|rocks|water|sand|📄',
  'Which one is sticky?|glue|a pencil|a ball|a book|🧴',
  'Which one is shiny?|a mirror|a log|a brick|a sack|🪞',
  'Which one is heavy?|a big rock|a feather|a leaf|paper|🪨',
  'Which one is light?|a feather|a rock|a brick|a bucket of sand|🪶',
  'Which one is wet?|water|sand|a rock|a book|💧',
  'Which one is dry?|sand|rain|a river|juice|🏖️',
  'Which one is made of metal?|a key|a leaf|a candle|a cloud|🔑',
  'Which one is made of cloth?|a shirt|a rock|a cup|a spoon|👕',
  'We use a magnet to pick up…|iron things|paper|water|leaves|🧲',
]);

const HEALTH = parseFacts([
  'Which food is good for you?|a banana|candy|a soda|chips|🍌',
  'Which one helps keep your teeth healthy?|brushing|only candy|never eating|soda|🪥',
  'We should wash our hands before we…|eat|run|jump|sing|🧼',
  'How many times a day should we brush our teeth?|two|none|one every week|ten|🪥',
  'Which drink is best for you?|water|soda|candy juice|coffee|💧',
  'We need to sleep so our body can…|rest and grow|shrink|disappear|float|😴',
  'Which one gives us energy?|rice|a pencil|a toy|a rock|🍚',
  'Which one helps us grow strong?|milk|candy|chips|ice pops|🥛',
  'Fruits and vegetables give us…|vitamins|toys|shoes|gas|🥦',
  'Which is a healthy snack?|an apple|a candy bar|a soda|a cake|🍎',
  'When we are sick, we should…|rest|run a marathon|swim in mud|skip sleep|🛌',
  'We cover our mouth when we…|cough|sing|clap|laugh loudly|🤧',
  'A bath helps us stay…|clean|dirty|sleepy|hungry|🛁',
  'Playing outside makes our body…|strong|weak|sick|sleepy forever|⚽',
  'Which one is a good habit?|washing hands|picking your nose|biting nails|skipping baths|🧼',
  'Which food comes from animals?|egg|rice|carrot|apple|🥚',
  'Which food comes from plants?|rice|egg|milk|fish|🍚',
  'Which meal do we eat in the morning?|breakfast|dinner|supper|midnight snack|🍳',
  'Too much candy can hurt our…|teeth|ears|eyes|hair|🍬',
  'We wear a helmet on a bike to protect our…|head|knees|toes|hands|⛑️',
  'We should look both ways before we…|cross the street|brush|sleep|read|🚸',
  'Which one is NOT safe?|touching a hot stove|holding hands|looking both ways|wearing a helmet|🔥',
  'When we feel sick, we should tell a…|grown-up|toy|stranger|bird|👩‍⚕️',
  'A doctor helps us stay…|healthy|loud|hungry|messy|🩺',
]);

const MATTER = parseFacts([
  'Ice is water that is…|frozen|boiling|invisible|a plant|🧊',
  'When ice gets warm, it…|melts|grows|barks|sings|🧊',
  'Water is a…|liquid|solid|bird|plant|💧',
  'A rock is a…|solid|liquid|gas|cloud|🪨',
  'Air is a…|gas|solid|liquid|rock|🌬️',
  'Steam is water as a…|gas|solid|rock|bird|♨️',
  'Which one can be poured?|juice|a stone|a book|a shoe|🧃',
  'Which one keeps its own shape?|a block|water|juice|air|🧱',
  'A balloon is filled with…|air|rocks|sand|bread|🎈',
  'We cannot see…|air|a tree|a cat|a book|🌬️',
  'Which one is boiling?|hot water bubbling|ice|a rock|a cloud|♨️',
  'Water changes into ice when it is very…|cold|hot|loud|bright|🥶',
  'A puddle dries up because the water…|goes into the air|runs away on legs|turns to stone|sleeps|☀️',
  'Where does rain come from?|clouds|rocks|the grass|a toy|🌧️',
  'What do we need to drink to stay alive?|water|sand|paper|glue|🚰',
  'Which is salty water?|the sea|the rain|a puddle|juice|🌊',
  'Which one dissolves in water?|sugar|a stone|a stick|a coin|🍬',
  'Which one does NOT dissolve in water?|a stone|salt|sugar|juice powder|🪨',
  'Wind is moving…|air|water|sand|light|💨',
  'Which one fills a balloon?|air|a stone|a book|a rug|🎈',
  'The place where rivers end is the…|sea|mountain|desert|roof|🌊',
  'Frozen water in the sky can fall as…|hail|sand|leaves|sugar|🧊',
  'Water in a pond is…|fresh|a rock|ice cream|a gas|🏞️',
  'To dry wet clothes, we hang them in the…|sun|fridge|cave|water|👕',
]);

const FORCES = parseFacts([
  'We use a push to…|move a door|read a book|watch TV|sleep|🚪',
  'We use a pull to…|open a drawer|kick a ball far|hit a nail|bake bread|🗄️',
  'A magnet can pull…|a paper clip|a leaf|a cloth|a candle|🧲',
  'Which one makes sound?|a drum|a rock|a pillow|a cup|🥁',
  'Sound travels to our…|ears|toes|knees|elbows|👂',
  'Which one makes light?|a lamp|a rock|a box|a table|💡',
  'The Sun gives us…|light and heat|snow|rocks|toys|☀️',
  'When we turn off the light, the room is…|dark|bright|loud|wet|🌑',
  'A shadow is made when something blocks the…|light|sound|smell|taste|🌳',
  'Which is louder?|a siren|a whisper|a pin dropping|a feather landing|🚨',
  'Which is quieter?|a whisper|a siren|a drum|a horn|🤫',
  'A ball rolls down a hill because of…|gravity|a magnet|a battery|wind only|⚽',
  'When you drop a pencil, it falls…|down|up|sideways|away forever|✏️',
  'We use a battery to make a toy…|work|sleep|melt|swim|🔋',
  'A swing moves when we…|push it|sing at it|read to it|paint it|🎠',
  'A kite flies because of the…|wind|moon|rain|snow|🪁',
  'A boat moves on water with oars or…|a sail|a fork|a pillow|a lamp|⛵',
  'Which is a simple tool for cutting paper?|scissors|a spoon|a cup|a pillow|✂️',
  'We use a hammer to…|hit a nail|read|eat soup|paint|🔨',
  'We use a fan to feel…|cool air|snow|rain|fire|🪭',
  'The faster you push a swing, the…|higher it goes|lower it goes|quieter it is|colder it is|🎠',
  'A bell rings when it is…|hit|read|watered|painted|🔔',
  'A flashlight needs…|batteries|water|seeds|soil|🔦',
  'Which one is moving?|a rolling ball|a sleeping cat|a closed book|a still rock|⚽',
]);

const EARTH = parseFacts([
  'What covers most of the Earth?|water|sand|snow|grass|🌍',
  'A big hill is a…|mountain|puddle|cup|pond|⛰️',
  'A big flow of water is a…|river|rock|hill|cave|🏞️',
  'The Philippines is made of many…|islands|deserts|glaciers|volcanoes only|🏝️',
  'A volcano can send out…|hot lava|ice|snow|candy|🌋',
  'Mayon is a famous…|volcano|river|beach|lake|🌋',
  'Where can we find sand?|a beach|a mountain top|a cloud|a tree|🏖️',
  'Soil helps plants…|grow|fly|sing|sleep|🌱',
  'A strong shaking of the ground is an…|earthquake|rainbow|sunrise|breeze|🌋',
  'During an earthquake, we should…|duck, cover and hold|run into a tree|swim|climb a roof|🧍',
  'Which one is a natural light at night?|the Moon|a lamp|a candle|a flashlight|🌙',
  'Rocks come in many…|sizes and colors|voices|songs|tastes|🪨',
  'We should take care of the Earth by…|not littering|throwing trash|cutting all trees|wasting water|♻️',
  'We should put trash in the…|trash bin|river|street|garden|🗑️',
  'We save water by…|turning off the tap|leaving it on|playing in the tap|never washing|🚰',
  'We save energy by turning off the…|light when not needed|fridge always|moon|sun|💡',
  'Recycling helps…|the Earth|make more trash|make noise|waste water|♻️',
  'A plastic bottle can be…|recycled|eaten|planted|worn on the head|🍼',
  'Trees help give us…|fresh air|more trash|loud noise|plastic|🌳',
  'A forest is a place with many…|trees|cars|shops|toys|🌲',
  'A pond is a small body of…|water|sand|rocks|ice cream|🏞️',
  'A lake is…|bigger than a pond|smaller than a puddle|made of milk|a tiny drop|🏞️',
  'The ocean is made of…|salt water|fresh water only|sand|paper|🌊',
  'Dirty water can make us…|sick|strong|taller|sleepy|🤢',
]);

export function scienceLevels(): LevelDef[] {
  const sub = 'science' as const;
  return [
    ...topicLevels({ subject: sub, topicNo: 1, topic: 'Animals', emoji: '🐾', blurb: 'Animals and their babies.', facts: ANIMALS }),
    ...topicLevels({ subject: sub, topicNo: 2, topic: 'Plants', emoji: '🌱', blurb: 'Parts of a plant and what it needs.', facts: PLANTS }),
    ...topicLevels({ subject: sub, topicNo: 3, topic: 'My body', emoji: '🧍', blurb: 'My body and my five senses.', facts: BODY }),
    ...topicLevels({ subject: sub, topicNo: 4, topic: 'Weather', emoji: '🌦️', blurb: 'Sun, rain, wind and seasons.', facts: WEATHER }),
    ...topicLevels({ subject: sub, topicNo: 5, topic: 'Sky and space', emoji: '🌙', blurb: 'The Sun, Moon, stars and planets.', facts: SKY }),
    ...topicLevels({ subject: sub, topicNo: 6, topic: 'Caring for Earth', emoji: '🌍', blurb: 'Rivers, mountains and looking after nature.', facts: EARTH }),
    ...topicLevels({ subject: sub, topicNo: 7, topic: 'Materials', emoji: '🧱', blurb: 'Hard, soft, float and sink.', facts: MATERIALS }),
    ...topicLevels({ subject: sub, topicNo: 8, topic: 'Healthy habits', emoji: '🍎', blurb: 'Food, sleep and staying safe.', facts: HEALTH }),
    ...topicLevels({ subject: sub, topicNo: 9, topic: 'Water and air', emoji: '💧', blurb: 'Solid, liquid and gas.', facts: MATTER }),
    ...topicLevels({ subject: sub, topicNo: 10, topic: 'Push, pull and light', emoji: '🧲', blurb: 'Pushes, pulls, sound and light.', facts: FORCES }),
  ];
}

