import { getDb } from '@/database/db';
import { summaryRepo, weekRange } from '@/database/repositories/summaryRepo';
import { routinesRepo } from '@/database/repositories/routinesRepo';
import { notesRepo } from '@/database/repositories/notesRepo';
(async () => {
  const db = await getDb();
  const now = new Date().toISOString();
  await db.runAsync("INSERT INTO speech_practice_events (activity_id, kind, item, duration_ms, created_at) VALUES ('words','exercise','Ball',0,?),('words','attempt','ball',0,?),('words','exercise','Cup',0,?),('syllables','exercise','BA',0,?),('words','session','',60000,?)", now, now, now, now, now);
  await db.runAsync("INSERT INTO sound_practice_attempts (sound_id, level, item, duration_ms, created_at) VALUES ('b','sound','B',0,?),('b','sound','B',0,?),('m','sound','M',0,?)", now, now, now);
  await db.runAsync("INSERT INTO star_events (amount, reason, source, created_at) VALUES (5,'x','learning',?),(-3,'r','reward',?)", now, now);
  const items = await routinesRepo.getActiveItems?.() ?? [];
  const first: any = (await db.getAllAsync('SELECT id FROM routine_items LIMIT 2'));
  for (const r of first) await routinesRepo.setItemDone(r.id, true);
  const w = await summaryRepo.weekly(weekRange(0), 1);
  console.log(JSON.stringify(w, null, 1));
  console.log(await summaryRepo.today(), await summaryRepo.starsEarnedSince(weekRange(0).startIso));
  await notesRepo.create({ noteType: 'speech', title: '', body: 'Practiced B', photoUri: null, noteDate: '2026-09-20' });
  console.log((await notesRepo.getAll())[0]);
  const ok = w.speechSessions === 3 && w.wordsPracticed === 2 && w.soundsPracticed === 2 && w.starsEarned === 5 && w.routineSteps === first.length && w.topSound?.soundId === 'b' && w.newWords === 2;
  console.log(ok ? 'ALL OK' : 'MISMATCH');
})().catch((e) => { console.error(e); process.exit(1); });
