import type { Collectible, CollectionCategory, CollectionMetric, Destination, Rarity } from './registry';

/**
 * THE BIG EXPANSION: 166 more collectibles across all six rarities (Common to Mythic). Written as compact
 * rows (`rarity|name|emoji|fun fact`) per category, then expanded into full `Collectible`s here, so the
 * unlock rules are generated by ONE formula instead of 166 hand-typed numbers:
 *
 *  - Common..Legendary: a VERIFIED metric (sounds, words, Play & Learn plays, lessons, tracing pages, voice
 *    practice, My Day steps, stars, streak, Talk taps, Daily Missions, speech practice) at a threshold that
 *    rises with the rarity. The metric rotates item by item, so no single activity unlocks everything.
 *  - Mythic: the rarest tier is earned by FINDING MANY OTHER collectibles (100, 120 ... 200), so it can only
 *    come from sustained, real practice.
 *
 * Art is the emoji (offline-safe, like the learning content) on a rarity-coloured plate: `emoji:<char>`.
 */
const R: Record<string, Rarity> = { c: 'common', u: 'uncommon', r: 'rare', e: 'epic', l: 'legendary', m: 'mythic' };
const TIER: Record<Rarity, number> = { common: 0, uncommon: 1, rare: 2, epic: 3, legendary: 4, mythic: 5 };

/** Thresholds per metric, by rarity (common .. legendary). */
const SCALE: { metric: CollectionMetric; at: number[]; hint: (n: number) => string; to: Destination }[] = [
  { metric: 'sounds', at: [10, 12, 15, 25, 30], hint: (n) => `Practise ${n} different sounds.`, to: 'speech' },
  { metric: 'words', at: [6, 8, 10, 15, 25], hint: (n) => `Practise ${n} different words.`, to: 'speech' },
  { metric: 'quizzes', at: [12, 15, 20, 30, 50], hint: (n) => `Finish ${n} Play & Learn activities.`, to: 'learn' },
  { metric: 'lessons', at: [6, 7, 8, 10, 15], hint: (n) => `Finish ${n} lessons.`, to: 'lessons' },
  { metric: 'tracingSessions', at: [6, 7, 10, 12, 20], hint: (n) => `Finish ${n} tracing pages.`, to: 'trace' },
  { metric: 'practiceSessions', at: [4, 5, 6, 8, 12], hint: (n) => `Finish ${n} Listen & Talk practice sessions.`, to: 'voice' },
  { metric: 'routineSteps', at: [4, 5, 8, 12, 20], hint: (n) => `Do ${n} steps of My Day.`, to: 'myday' },
  { metric: 'stars', at: [60, 80, 100, 150, 250], hint: (n) => `Earn ${n} stars in total.`, to: 'progress' },
  { metric: 'streak', at: [2, 3, 4, 7, 10], hint: (n) => `Practise ${n} days in a row.`, to: 'progress' },
  { metric: 'talkTaps', at: [15, 20, 30, 50, 100], hint: (n) => `Say ${n} things with Talk.`, to: 'talk' },
  { metric: 'missionDays', at: [2, 4, 5, 7, 10], hint: (n) => `Complete the Daily Mission on ${n} days.`, to: 'mission' },
  { metric: 'speechPractice', at: [5, 8, 12, 20, 40], hint: (n) => `Do ${n} steps of Speech Practice.`, to: 'speech' },
];

const ROWS: Record<CollectionCategory, string[]> = {
  companions: [
    'c|Space Duckling|🐥|Space Duckling paddles through clouds of star dust.',
    'c|Moon Mouse|🐭|Moon Mouse nibbles on cheese-shaped craters.',
    'c|Comet Kitten|🐱|Comet Kitten chases its own glowing tail.',
    'c|Rocket Hamster|🐹|Rocket Hamster runs in a wheel to power the ship.',
    'c|Star Chick|🐤|Star Chick hatched from an egg that fell from a comet.',
    'c|Little Comet Bear|🐻|Little Comet Bear loves to nap under the northern lights.',
    'u|Nebula Fox|🦊|Nebula Fox has a tail that glitters like space dust.',
    'u|Starlight Owl|🦉|Starlight Owl stays awake all night to watch the stars.',
    'u|Gravity Frog|🐸|Gravity Frog leaps from one moon to the next.',
    'u|Orbit Penguin|🐧|Orbit Penguin slides across icy moons.',
    'u|Planet Pig|🐷|Planet Pig rolls in soft, squishy moon dust.',
    'u|Asteroid Hedgehog|🦔|Asteroid Hedgehog curls up like a tiny space rock.',
    'r|Lunar Koala|🐨|Lunar Koala naps on a crescent moon.',
    'r|Cosmic Turtle|🐢|Cosmic Turtle carries a tiny galaxy on its shell.',
    'r|Solar Lion|🦁|Solar Lion has a mane that glows like the Sun.',
    'r|Meteor Monkey|🐵|Meteor Monkey swings between floating rocks.',
    'r|Cosmic Otter|🦦|Cosmic Otter floats on its back among the stars.',
    'r|Meteor Bee|🐝|Meteor Bee makes honey that tastes like stardust.',
    'e|Galaxy Unicorn|🦄|Galaxy Unicorn leaves a rainbow trail across the sky.',
    'e|Aurora Wolf|🐺|Aurora Wolf howls and the sky lights up in green.',
    'e|Cosmic Dragon|🐲|Cosmic Dragon breathes sparkling star fire.',
    'e|Moonlight Swan|🦢|Moonlight Swan glides across a lake of silver light.',
    'l|Star Phoenix|🦅|The Star Phoenix glows bright, then rises again.',
    'l|Great Space Whale|🐋|The Great Space Whale sings songs between galaxies.',
    'l|Galaxy Elephant|🐘|The Galaxy Elephant never forgets a single star.',
    'm|Galaxy Guardian Dragon|🐉|The Galaxy Guardian watches over every friendly star.',
  ],
  planets: [
    'c|Uranus|🪐|Uranus spins tipped over on its side.',
    'c|Pluto|🌑|Pluto is a small, icy dwarf planet.',
    'c|Full Moon|🌕|A full moon is a bright, round circle in the night sky.',
    'c|Crescent Moon|🌙|A crescent moon looks like a glowing smile.',
    'c|Blue Marble|🌍|From space, Earth looks like a blue marble.',
    'c|Sunny Planet|☀️|A sunny planet is warm and bright all day.',
    'u|Europa|🌕|Europa is an icy moon of Jupiter with an ocean hiding underneath.',
    'u|Titan|🌖|Titan is a big orange moon of Saturn with thick air.',
    'u|Io|🌗|Io is a moon covered in bubbling volcanoes.',
    'u|Ganymede|🌘|Ganymede is the biggest moon in our solar system.',
    'u|Dusty Red Moon|🔴|The Dusty Red Moon glows like a ripe tomato.',
    'u|Frosty Moon|❄️|The Frosty Moon is covered in sparkling ice.',
    'r|Phobos|🌑|Phobos is a lumpy little moon that zooms around Mars.',
    'r|Deimos|🌚|Deimos is the smaller moon of Mars.',
    'r|Callisto|🌝|Callisto is a moon covered in craters.',
    'r|Enceladus|🌕|Enceladus squirts fountains of ice into space.',
    'r|Triton|🌑|Triton is a frozen moon that circles Neptune backwards.',
    'r|Storm Planet|🌪️|The Storm Planet has swirling clouds as big as oceans.',
    'r|Cloud Planet|☁️|The Cloud Planet is wrapped in soft, fluffy clouds.',
    'e|Ringed Ice Giant|🪐|The Ringed Ice Giant glitters with frozen rings.',
    'e|Lava World|🌋|The Lava World glows with rivers of hot rock.',
    'e|Water World|🌊|The Water World is one giant ocean.',
    'e|Ice World|🧊|The Ice World is frozen from pole to pole.',
    'e|Rainbow Planet|🌈|The Rainbow Planet shines in every colour.',
    'e|Crystal Moon|💠|The Crystal Moon sparkles like a giant gem.',
    'l|Twin Suns Planet|🌞|The Twin Suns Planet has two sunsets every evening.',
    'l|Diamond Planet|💎|The Diamond Planet glitters from top to bottom.',
    'm|The Hidden Ninth Planet|🪐|Only the most patient explorers ever find the Hidden Ninth Planet.',
  ],
  vehicles: [
    'c|Mini Rocket|🚀|The Mini Rocket is small but zooms very fast.',
    'c|Space Scooter|🛴|The Space Scooter glides over the Moon.',
    'c|Hover Bike|🏍️|The Hover Bike floats just above the ground.',
    'c|Moon Buggy|🚙|The Moon Buggy bumps along over craters.',
    'c|Space Skateboard|🛹|The Space Skateboard rolls on beams of light.',
    'u|Space Taxi|🚕|The Space Taxi takes astronauts from star to star.',
    'u|Space Bus|🚌|The Space Bus has seats for the whole crew.',
    'u|Star Ferry|⛴️|The Star Ferry crosses the gaps between planets.',
    'u|Space Train|🚄|The Space Train races along a track of starlight.',
    'u|Star Kayak|🛶|The Star Kayak paddles through rivers of stardust.',
    'r|Sky Jet|✈️|The Sky Jet climbs higher than any cloud.',
    'r|Comet Skimmer|🛩️|The Comet Skimmer surfs along a comet tail.',
    'r|Asteroid Miner|🚜|The Asteroid Miner digs for shiny space rocks.',
    'r|Space Tug|🚛|The Space Tug pulls big ships through space.',
    'r|Rescue Chopper|🚁|The Rescue Chopper helps explorers who are stuck.',
    'r|Orbit Cable Car|🚡|The Orbit Cable Car glides high above a planet.',
    'r|Moon Tram|🚊|The Moon Tram rattles between moon bases.',
    'e|Warp Drive Ship|🛸|The Warp Drive Ship bends space to travel fast.',
    'e|Space Ark|🚢|The Space Ark carries friends to a new world.',
    'e|Solar Sailer|⛵|The Solar Sailer is pushed along by sunlight.',
    'e|Space Elevator|🛗|The Space Elevator rides all the way up to the stars.',
    'e|Galaxy Submarine|🚤|The Galaxy Submarine dives into oceans on far-away moons.',
    'l|Star Carrier|🛰️|The Star Carrier is as big as a floating city.',
    'l|Hyperdrive Rocket|🚀|The Hyperdrive Rocket crosses a galaxy in a blink.',
    'l|Mothership|🛸|The Mothership glows over the whole sky.',
    'm|Rainbow Starship|🚀|The Rainbow Starship leaves a trail of every colour.',
  ],
  discoveries: [
    'c|Star Dust|✨|Star dust is the tiny sparkle left by old stars.',
    'c|Sunbeam|☀️|A sunbeam takes about eight minutes to reach Earth.',
    'c|Little Spark|💫|A little spark twirls through the dark.',
    'c|Space Rainbow|🌈|A space rainbow bends across the sky.',
    'c|Twinkle|🌟|Twinkle is the smallest star in the sky.',
    'c|Space Bubble|🫧|A space bubble floats through the stars.',
    'u|Solar Flare|🔥|A solar flare is a burst of light from the Sun.',
    'u|Cosmic Ray|⚡|A cosmic ray is a tiny, super-fast zap of energy.',
    'u|Asteroid|🪨|An asteroid is a space rock that circles the Sun.',
    'u|Ice Comet|🧊|An ice comet is a frozen snowball flying through space.',
    'u|Star Cluster|⭐|A star cluster is a big family of stars.',
    'u|Ice Crystal|❄️|An ice crystal sparkles on the back of a comet.',
    'r|Pulsar|🌟|A pulsar blinks like a lighthouse in space.',
    'r|Quasar|💥|A quasar shines brighter than a whole galaxy.',
    'r|Dwarf Star|⭐|A dwarf star is small, warm and long-lived.',
    'r|Red Giant|🔴|A red giant is a huge, glowing old star.',
    'r|Blue Star|🔵|A blue star burns very hot and bright.',
    'r|Magnetar|🧲|A magnetar is a star with a super-strong magnet.',
    'r|Gas Cloud|☁️|A gas cloud is where new stars are born.',
    'e|Supernova|💥|A supernova is a giant star-sized sparkle.',
    'e|Aurora Lights|🌌|Aurora lights dance in green and pink.',
    'e|Wormhole|🌀|A wormhole is a pretend tunnel through space.',
    'e|Dark Matter|⚫|Dark matter is invisible, but it holds galaxies together.',
    'e|Neutron Star|⚪|A neutron star is tiny but very, very heavy.',
    'e|Cosmic Web|🕸️|The cosmic web links every galaxy with threads of gas.',
    'l|Galaxy Spiral|🌌|A spiral galaxy turns slowly like a pinwheel.',
    'l|Big Bang Spark|🎆|Everything began with one giant spark.',
    'l|Event Horizon|🕳️|The event horizon is the edge of a black hole.',
    'm|Heart of the Universe|💖|The Heart of the Universe is the rarest discovery of all.',
  ],
  equipment: [
    'c|Space Glove|🧤|A space glove keeps hands warm and safe.',
    'c|Star Map|🗺️|A star map shows the way between planets.',
    'c|Flashlight|🔦|A flashlight helps explorers see in dark craters.',
    'c|Space Snack|🍪|A space snack gives astronauts energy.',
    'c|Space Spoon|🥄|A space spoon helps with floating dinners.',
    'c|Star Pen|🖊️|A star pen writes notes about new discoveries.',
    'u|Oxygen Tank|🫧|An oxygen tank carries air to breathe.',
    'u|Moon Camera|📷|A moon camera takes pictures of faraway places.',
    'u|Space Radio|📻|A space radio talks to friends back home.',
    'u|Space Compass|🧭|A space compass points toward the next adventure.',
    'u|Space Notebook|📓|A space notebook holds drawings of new friends.',
    'u|Solar Panel|🔆|A solar panel turns sunshine into power.',
    'r|Antenna Dish|📡|An antenna dish listens for messages from space.',
    'r|Space Goggles|🥽|Space goggles keep stardust out of your eyes.',
    'r|Power Cell|🔋|A power cell keeps the ship humming.',
    'r|Tool Kit|🧰|A tool kit fixes anything on a space trip.',
    'r|Space Drill|🔧|A space drill digs into moon rocks.',
    'r|Jet Boots|🥾|Jet boots help explorers bound across craters.',
    'r|Moon Shovel|⛏️|A moon shovel scoops up shiny moon rocks.',
    'e|Gravity Boots|👢|Gravity boots stick to the floor of a spaceship.',
    'e|Hologram Map|🗺️|A hologram map floats in the air.',
    'e|Laser Lantern|🏮|A laser lantern lights up whole caves.',
    'e|Gravity Hammer|🔨|A gravity hammer taps rocks into place.',
    'e|Star Lantern|💡|A star lantern glows with captured starlight.',
    'l|Starlight Compass|🧭|The Starlight Compass always points to home.',
    'l|Time Lens|🔍|The Time Lens shows the stars as they used to be.',
    'm|Cosmic Crown|👑|The Cosmic Crown belongs to a true star explorer.',
  ],
  special: [
    'c|Space Sticker|🏷️|A space sticker for the best explorers.',
    'c|Lucky Star|⭐|A lucky star brings good fortune.',
    'c|Moon Cheese|🧀|Some people joke that the Moon is made of cheese.',
    'c|Space Balloon|🎈|A space balloon floats up, up and away.',
    'c|Space Pizza|🍕|Space pizza is the favourite food of the crew.',
    'c|Star Cake|🎂|A star cake is baked for a big space party.',
    'u|Message in a Bottle|🍾|A message in a bottle drifts between the planets.',
    'u|Space Postcard|💌|A space postcard says hello from the Moon.',
    'u|Starry Flag|🚩|A starry flag marks a brand-new discovery.',
    'u|Golden Ticket|🎫|A golden ticket opens the door to a space show.',
    'u|Cosmic Candy|🍬|Cosmic candy sparkles on your tongue.',
    'u|Moon Pie|🥧|A moon pie is round like a full moon.',
    'r|Mystery Gift|🎁|Nobody knows what is inside the Mystery Gift.',
    'r|Crystal Ball|🔮|The Crystal Ball shows swirling galaxies.',
    'r|Ancient Scroll|📜|The Ancient Scroll tells of the very first stars.',
    'r|Secret Key|🗝️|The Secret Key opens a hidden space door.',
    'r|Space Potion|🧪|The Space Potion bubbles and glows.',
    'r|Galaxy Dance|💃|The Galaxy Dance is a twirl under the stars.',
    'r|Space Music|🎵|Space music hums between the planets.',
    'e|Treasure Map|🗺️|The Treasure Map leads to a hidden asteroid.',
    'e|Sparkling Medal|🎖️|The Sparkling Medal is for brave explorers.',
    'e|Alien Treasure|💎|The Alien Treasure is a gift from a faraway friend.',
    'e|Cosmic Fireworks|🎆|Cosmic fireworks light up the whole night.',
    'e|Magic Hat|🎩|The Magic Hat pulls out a rabbit made of stars.',
    'l|Champion Trophy|🏆|The Champion Trophy shines for the best explorers.',
    'l|Golden Galaxy Key|🔑|The Golden Galaxy Key opens every door in space.',
    'l|Lucky Comet|🌠|The Lucky Comet only visits once in a very long time.',
    'm|Universe Master Medal|🥇|The Universe Master Medal is for the greatest explorer ever.',
    'm|Everything Star|🌟|The Everything Star holds a piece of every other star.',
  ],
};

/**
 * The unlock rule for the n-th (0-based) collectible of a rarity: a verified metric whose threshold rises with the
 * rarity and, slowly, with n (capped at 4x), so a thousand items are a long road and never an impossible one.
 * Mythic is "find N others"; the registry spaces those thresholds evenly once it knows the total.
 */
export function ruleFor(rarity: Rarity, n: number): Pick<Collectible, 'condition' | 'hint' | 'destination'> {
  if (rarity === 'mythic') return { condition: { kind: 'collected', at: 100 }, hint: 'Find 100 collectibles.', destination: 'progress' };
  const s = SCALE[n % SCALE.length];
  const at = Math.round(s.at[TIER[rarity]] * Math.min(4, 1 + 0.05 * Math.floor(n / SCALE.length)));
  return { condition: { kind: 'metric', metric: s.metric, at }, hint: s.hint(at), destination: s.to };
}

/** Running count per rarity, shared with the generated expansion so thresholds keep climbing across both. */
export const RARITY_COUNTS: Record<Rarity, number> = { common: 0, uncommon: 0, rare: 0, epic: 0, legendary: 0, mythic: 0 };

function expand(): Collectible[] {
  const out: Collectible[] = [];
  for (const category of Object.keys(ROWS) as CollectionCategory[]) {
    for (const row of ROWS[category]) {
      const [r, name, emoji, fact] = row.split('|');
      const rarity = R[r];
      const n = RARITY_COUNTS[rarity]++;
      const id = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      out.push({ id, name, category, rarity, art: `emoji:${emoji}`, fact, ...ruleFor(rarity, n) });
    }
  }
  return out;
}

export const EXTRA_COLLECTION: Collectible[] = expand();
